### ISSUE TITLE
Compile on Ubuntu

### ISSUE THREAD

**Issue by taiamiti** [GravisZro/ASIP#2]
Hello, first of all thank you for the great work. I was wondering if you could share your build configuration on ubuntu because I couldn't compile the code with cmake due to dependency versions issues. I have installed the latest dependencies but I have seen some have breaking changes in recent versions. More detailled instructions to build the project are much appreciated. 

Also, is there an equivalent python code used for prototyping ?

**Comment by GravisZro** [comment]
Here's the thing... this isn't my code, I just put it on github.
